version: '3'

services:
  db:
    image: postgres:14.6-alpine
    container_name: db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - envs/local/postgres

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    command: redis-server
    volumes:
      - ./redis/data:/var/lib/redis/data
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    command:
      - sh "python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py loaddata data.json &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/var/backend
    env_file:
      - envs/local/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis